### PR TITLE
Add ZSH and bash completion scripts

### PR DESCRIPTION
**Pull request by Arkanosis**
This is a first draft and while it's not perfect, it does 80% of what one would expect from shell completion. The bash version in particular needs some love, as I'm a zsh user myself — but I thought I might as well bootstrap something for others to build on.

### CODE REVIEW

**Comment by claudiodangelis** [comment]
@Arkanosis thanks for your effort on this, it is something I wanted to add sooner or later. I will find some time in the next few days to have a look at this pull request. 

By the way, the command line is built with cobra, are you familiar with it? Maybe you can find useful information about bash completion on their docs: https://github.com/spf13/cobra/blob/master/bash_completions.md 

Cheers, 
Claudio

**Comment by Arkanosis** [comment]
> @Arkanosis thanks for your effort on this, it is something I wanted to add sooner or later. I will find some time in the next few days to have a look at this pull request.

Thank you!

> By the way, the command line is built with cobra, are you familiar with it?

I've never used it, unfortunately. But if the completion script can be generated, that's definitely better than trying to keep the completion in sync with new version manually! :)

**Comment by claudiodangelis** [comment]
Hello @Arkanosis, it seems that the generation of shell completion scripts with `cobra` is really straightforward, I will close this PR now and will open a new one with the generated scripts.

Thank you again for your effort on this.

**Comment by Arkanosis** [comment]
Hello @claudiodangelis :) Sorry for the late reply. That's great to hear! Thanks!

**Pull request closed without merging**
