### PR TITLE
Upgrade cobra to v1.2.1

### PR DESCRIPTION
**Pull request by Holi0317**
[Cobra changelog](https://github.com/spf13/cobra/releases) says there is no breaking change.

The upgrade includes a revamp on zsh completion script which greatly improve usability of qrcp.

Before the upgrade, the zsh tab completion will not include files after typing `send` command.

[asciicast - qrcp with cobra 1.0.0](https://asciinema.org/a/429226)

After the upgrade, the zsh tab completion will include files after typing `send` command. Which should
greatly improve the user experience when using the command.

[asciicast - qrcp with cobra 1.2.1](https://asciinema.org/a/429224)

### CODE REVIEW

**Comment by solarfl4re** [comment]
I cloned qrcp locally just to apply your change, filename completion is a must-have.

**Comment by claudiodangelis** [comment]
Hi! Sorry for the super wait! This will be released as per the upcoming `0.10.0` version.
Thank you! :pray:

**Comment by claudiodangelis** [comment]
Oh, it looks like the current stable is 1.6.0 now: https://github.com/spf13/cobra/releases/tag/v1.6.0

I will push the change to your fork soon.

Thanks,
C

**Comment by claudiodangelis** [comment]
Hello, since this PR is quite old, I will move on and close it.
Thanks for taking the time to report it in the first place!
Claudio

**Pull request closed without merging**
